version: '3.8'

services:
  app:
    build: .
    container_name: cherry-ohlcv
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - LOG_LEVEL=info
      - CLICKHOUSE_URL=${CLICKHOUSE_URL}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - REDIS_URL=redis://redis:6379
      - RATE_LIMIT_POINTS=120
      - RATE_LIMIT_DURATION=60
      - API_TIMEOUT=30000
      - TELEGRAM_BOT_TOKEN=8087435064:AAEWETcMIHkIL7SI2OtO5Rg_Rq-Q-D7lxzQ
      - TELEGRAM_CHAT_ID=1872497855
    depends_on:
      - redis
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - .:/app  # Mount the current directory to the container for live code updates
    command: ["nodemon", "dist/index.js"]  # Use nodemon to automatically restart the app

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped  

networks:
  app-network:
    driver: bridge